name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - 5.x
  pull_request:
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    name: ci
    uses: craftcms/.github/.github/workflows/ci.yml@v3
    with:
      php_version: '8.2'
      craft_version: '5'
      node_version: '20'
      jobs: '["ecs", "prettier", "phpstan", "tests"]'
      notify_slack: true
      slack_subteam: <!subteam^SGFL9NKNZ>
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_CRAFT_WEBHOOK_URL }}

    # this can be moved to .github repo once this is proven works on CI
  rector:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          # PHP 8.2 is required, so Rector's code is PHP 8.2 compatible even after refactoring
          php-version: 8.2
          coverage: none

      - run: composer install --no-progress --ansi
      - run: vendor/bin/rector process --dry-run --ansi
